### ISSUE TITLE
FORCE_PASSWORD_CHANGE Exception Not Thrown if LDAP Authentication is Enabled

### ISSUE THREAD

**Issue by bernard-wagner** [stevespringett/Alpine#16]
After an initial deployment of dependency-track its is not possible to authenticate as the default admin due to the FORCE_PASSWORD_CHANGE exception never being thrown and LDAP authentication is attempted instead. 

https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/auth/Authenticator.java#L67
```
 }catch(AlpineAuthenticationException e){
             // If LDAP is enabled, a second attempt to authenticate the credentials will be made against LDAP so we skip this validation exception. 
            if (!LDAP_ENABLED) {
                throw e;
              }
        }
```

As stated in the code comment all ManagedUser exceptions are suppressed and never thrown if LDAP authentication is enabled.

Suggestion is to create different Exception types for different authentication errors.

**Comment by stevespringett** [comment]
Good find! Thanks for catching this. I've reproduced and confirmed the issue.
