### ISSUE TITLE
How to read and set encrypted properties?

### ISSUE THREAD

**Issue by feliceg77** [stevespringett/Alpine#23]

**Comment by feliceg77** [comment]
I want to encrypt entry in application.properties

**Comment by stevespringett** [comment]
If you're referring to [ConfigProperty.class](https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/model/ConfigProperty.java), property values can be encrypted by specifying [PropertyType.ENCRYPTEDSTRING](https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/model/IConfigProperty.java#L33) as the property type. Use [DataEncryption.class](https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/crypto/DataEncryption.java) for the actual encryption/decryption. At the moment, there isn't a class that does this for you automatically. However, [Dependency-Track](https://dependencytrack.org/), an application built on top of Alpine, does have a [JAX-RS resource](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java) that does implement this logic.

If you're referring to properties in application.properties. Encryption/decryption is currently not supported here but likely will be in a future release.
