### ISSUE TITLE
mvn clean install is not running out of the box

### ISSUE THREAD

**Issue by svenlange** [stevespringett/Alpine#28]
A `mvn clean install` results in the following error message.

`[ERROR] Failed to execute goal on project alpine-parent: Could not resolve dependencies for project us.springett:alpine-parent:pom:1.5.1-SNAPSHOT: The following artifacts could not be resolved: com.fasterxml.jackson.core:jackson-annotations:jar:2.9.9.1, com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.9.1, com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.9.1: Could not find artifact com.fasterxml.jackson.core:jackson-annotations:jar:2.9.9.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
`

**Comment by stevespringett** [comment]
Thanks for the report. Issue is fixed.
