### ISSUE TITLE
PaginatedResult setObject and object for Collections don't work

### ISSUE THREAD

**Issue by timmeinerzhagen** [stevespringett/Alpine#29]
<Class PaginatedResult>

    public void setObjects(Collection<?> object) {
        this.objects = objects;
    }
    public PaginatedResult objects(Collection<?> object) {
        this.objects = objects;
        return this;
    }

Both set the attribute to itself instead of the new parameter.

**Comment by stevespringett** [comment]
Thanks for catching this. 👍 The fix will be included in the next release.

**Comment by stevespringett** [comment]
Closing as this was resolved in 1.6.0
