### ISSUE TITLE
Update to Java 17

### ISSUE THREAD

**Issue by nscuro** [stevespringett/Alpine#383]
Besides the performance improvements and syntactic sugar introduced in Java 17 over Java 11, we should try to stay current by using the latest LTS release. There are some minor roadblocks when building with Java 17 right now. The main blocker right now is DataNucleus not supporting Java 17 in a stable version yet.

I tried to move Alpine and Dependency-Track to Java 17, here's what I've found so far:

- [x] Update to DataNucleus 6
  - Bytecode Enhancement for Java >= 16 is available since `6.0.0-m1` (https://github.com/datanucleus/datanucleus-core/issues/359)
  - With `6.0.0-m4`, build and test run fine. Dependency-Track works as expected as well. Doesn't look like there's much migration work to be done.
- [x] The `--illegal-access` flag [has been deprecated](https://openjdk.java.net/jeps/403) and doesn't have an effect anymore. This change mostly affects tests as far as I could tell. For example those that try to modify environment variables in some way:
    ```
    ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.054 s <<< FAILURE! - in alpine.common.util.ThreadUtilTest
    [ERROR] determineNumberOfWorkerThreadsTest(alpine.common.util.ThreadUtilTest)  Time elapsed: 0.008 s  <<< ERROR!
    java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @7530d0a
   ```
  - This is fixable by adding the following `configuration` to the surefire plugin:
    ```xml
    <argLine>--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED</argLine>
    ```

**Comment by stevespringett** [comment]
There's a note in the pom that states:

> DO NOT UPDATE Datanucleus RDBMS beyond 5.2.7 (for now) due to breaking changes introduced in https://github.com/datanucleus/datanucleus-rdbms/pull/375

I have been careful not to touch the RDBMS library as it breaks installations that use Postgres. I have not had an opportunity to find out root cause.

**Comment by nscuro** [comment]
As you have already noticed, the underlying issue has been fixed in DN and I raised a PR for an update to the latest 5.2.x versions in #382.

But it looks like DN is developed by a single person. Obviously they're doing an amazing job in keeping the project alive, but I can't help but wonder if that can become a problem.

**Comment by stevespringett** [comment]
From my understanding Datanucleus offers commercial support and Google is a large customer as GCP implements it. Unfortunately, it's one of the last remaining JDO implementations available.

**Comment by nscuro** [comment]
DataNucleus 6.0.0 was released a few days ago: https://www.datanucleus.org/documentation/news/access_platform_6_0.html#_datanucleus_accessplatform_6_0_0_release

Migration guide: https://www.datanucleus.org/products/accessplatform_6_0/migration.html

DN also supports H2 2.x now.
