### ISSUE TITLE
compile on windows

### ISSUE THREAD

**Issue by Pamir** [stevespringett/Alpine#5]
Hi,

In order to compile on windows, data-nucleus plugin needs fork option to be false. Otherwise it breaks the build by an _too many arguments error._ Could you please add a profile for windows builds.

<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <compilerArgs>
                        <arg>-Xlint:all</arg>
                        <arg>-Xlint:-processing</arg>
                        <arg>-Xlint:-serial</arg>
                        <arg>-Werror</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.datanucleus</groupId>
                <artifactId>datanucleus-maven-plugin</artifactId>
                <version>${maven.datanucleus.plugin.version}</version>
                <configuration>
                    <api>JDO</api>
                    <persistenceUnitName>Alpine</persistenceUnitName>
                    <verbose>true</verbose>
                     <fork>false</fork>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>enhance</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

**Comment by stevespringett** [comment]
Thanks for reporting. I'll try to reproduce and make the necessary correction.
