### ISSUE TITLE
Upgrade Surefire Plugin from 2.22.2 to Latest 3.x

### ISSUE THREAD

**Issue by msymons** [stevespringett/Alpine#538]
Alpine currently uses `maven-surefire-plugin` v2.22.2, the last 2.x release.

This plugin is not compatible with upcoming Maven 4.0.0 and should be upgraded to 3.x.  Currently, the most recent plugin release is v3.2.5

Running a build with parameter:  `-Dmaven.plugin.validation=verbose`  provides the following warnings for v2.22.2

```
 * org.apache.maven.plugins:maven-surefire-plugin:2.22.2
  Declared at location(s):
   * xxx
  Used in module(s):
   * yyy
  Plugin issue(s):
   * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
   * Plugin depends on plexus-container-default, which is EOL
  Mojo issue(s):
   * Mojo surefire:test (org.apache.maven.plugin.surefire.SurefirePlugin)
     - Parameter 'localRepository' uses deprecated parameter expression '${localRepository}': ArtifactRepository type is deprecated and its use in Mojos should be avoided.
```

I am logging this as an issue rather than simply providing a PR that updates the version in the POM as I am not a dev and @stevespringett reports that a previous attempt to upgrade the plugin gave problems and was aborted.

**Comment by nscuro** [comment]
Not sure what / if something changed since the last time this was attempted but #608 is passing and the DT test suite runs fine with it as well.
