### ISSUE TITLE
Please publish alpine-parent before dependency-track

### ISSUE THREAD

**Issue by markusmuellerusi** [stevespringett/Alpine#571]
<artifactId>alpine-parent</artifactId>
    <packaging>pom</packaging>
    <version>2.2.6-SNAPSHOT</version>

You cannot build without downloading this version from Maven or go back to latest available release and hope it will run.

**Comment by nscuro** [comment]
`2.2.6` was never released. Due to various breaking changes it was renamed to `3.0.0-SNAPSHOT`, and finally got released yesterday: https://github.com/stevespringett/Alpine/releases/tag/alpine-parent-3.0.1

Dependency-Track has already switched to the release version as of today.
